---
- name: chekc if spark tar exits
  stat:
    path: /tmp/spark-{{ spark_version }}-bin-hadoop2.7.tgz
  register: spark_result

- name: chekc if spark dircetory exits
  stat:
    path: /opt/spark-{{ spark_version }}-bin-hadoop2.7
  register: spark_dir_result

- name: chekc if spark tgz exits
  stat:
    path: /opt/spark-{{ spark_version }}.tgz
  register: spark_tgz_result

- name: Get spark tar
  get_url:
    url: https://d3kbcqa49mib13.cloudfront.net/spark-{{ spark_version }}-bin-hadoop2.7.tgz
    dest: /tmp/
  when: spark_result.stat.exists == False

- name: unarchive spark dircetory
  unarchive: 
    src: /tmp/spark-{{ spark_version }}-bin-hadoop2.7.tgz
    dest: /opt/
  when: spark_dir_result.stat.exists == False

- name: Create slaves
  template: src=slaves.j2 dest=/opt/spark-{{ spark_version }}-bin-hadoop2.7/conf/slaves 

- name: Create spark-env.sh 
  template: src=spark-env.sh.j2 dest=/opt/spark-{{ spark_version }}-bin-hadoop2.7/conf/spark-env.sh

- name: Create tar
  archive:
    path: /opt/spark-{{ spark_version }}-bin-hadoop2.7
    dest: /opt/spark-{{ spark_version }}.tgz
  when: spark_tgz_result.stat.exists == False
